[package]
name = "vcm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.54", features = ["derive"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
tonic = "0.12"
tower = "0.5"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
voice-controllm-daemon = { version = "0.1.0", path = "../daemon" }
voice-controllm-proto = { version = "0.1.0", path = "../proto" }
