[package]
name = "voice-controllm-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0.100"
audioadapter-buffers = "2.0.0"
cpal = "0.17.1"
dirs = "6.0.0"
rubato = "1.0.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
tracing = "0.1.44"

[dev-dependencies]
tempfile = "3.20"
